[build]
buildCommand = "npx prisma generate && npx prisma db push && npx tsx prisma/seed.ts && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/login"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
